attendance/urls.py
from django.urls import path
from attendance.views import AttendanceCreateView, AttendanceDetailView, AttendanceUpdateView, AttendanceStudentView


urlpatterns = [
    path('new/', AttendanceCreateView.as_view(), name='new'),
    path('', AttendanceDetailView.as_view(), name='detail'),
    path('update/', AttendanceUpdateView.as_view(), name='update'),
    path('search/', AttendanceStudentView.as_view(), name='search')
]

courses/urls.py
from django.urls import path
from courses.views import CourseListView, CourseCreateView, CourseUpdateView


urlpatterns = [
    path('', CourseListView.as_view(), name='list'),
    path('new/', CourseCreateView.as_view(), name='new'),
    path('edit/<int:pk>', CourseUpdateView.as_view(), name='edit')
]

kunai/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import (
    LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
)
from users.views import HomeView, UserLoginView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('attendance/', include(('attendance.urls', 'attendance'), namespace='attendance')),
    path('courses/', include(('courses.urls', 'courses'), namespace='courses')),
    path('feedback/', include(('feedback.urls', 'feedback'), namespace='feedback')),
    path('leaves/', include(('leaves.urls', 'leaves'), namespace='leaves')),
    path('notifications/', include(('notifications.urls', 'notifications'), namespace='notifications')),
    path('results/', include(('results.urls', 'results'), namespace='results')),
    path('session/', include(('session.urls', 'session'), namespace='session')),
    path('subjects/', include(('subjects.urls', 'subjects'), namespace='subjects')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('', HomeView.as_view(), name='home'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('password_reset/', PasswordResetView.as_view(template_name='password_reset.html'), name='password_reset'),
    path('password_reset_done/', PasswordResetDoneView.as_view(template_name='password_reset_done.html'), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'), name='password_reset_confirm'),
    path('password_reset_complete', PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), name='password_reset_complete'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users.views import StaffListView, StaffCreateView, StaffUpdateView, StudentListView, StudentCreateView, StudentUpdateView


urlpatterns = [
    path('staff/', StaffListView.as_view(), name='list_staff'),
    path('staff/new/', StaffCreateView.as_view(), name='new_staff'),
    path('staff/edit/<int:pk>', StaffUpdateView.as_view(), name='edit_staff'),
    path('students/', StudentListView.as_view(), name='list_student'),
    path('students/new/', StudentCreateView.as_view(), name='new_student'),
    path('students/edit/<int:pk>', StudentUpdateView.as_view(), name='edit_student'),
]

templates/staff/components/footer.html
<footer class="footer pt-3 pd-2 px-md-5">
  <p class="text-center">
    Copyright &copy;
    <script>
      document.write(new Date().getFullYear());
    </script>
    All rights reserved
  </p>
</footer>

templates/staff/components/messages.html
{% if messages %}
{% for message in messages %}
<div class="alert alert-{{ message.tags }}">
  {{ message }}
</div>
{% endfor %}
{% endif %}

templates/staff/components/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-light">
  <div class="container-fluid">
    <button type="button" id="sidebarCollapse" class="btn btn-pill btn-sidebar">
      <i class="fa fa-bars"></i>
      <span class="sr-only">Toggle Menu</span>
    </button>
    <button class="btn btn-pill btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse"
      data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
      aria-label="Toggle navigation">
      <i class="fa fa-bars"></i>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="nav navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="javascript:void(0)" data-toggle="modal" data-target="#logout-modal">Logout</a>
        </li>

        <div class="modal fade" id="logout-modal" tabindex="-1" role="dialog" aria-labelledby="logout-modal"
          aria-hidden="true">
          <div class="modal-dialog my-5" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title">Logout?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>

              <div class="modal-body">
                Are you sure you want to logout?
                <form id="logout-form" method="POST" action="{% url 'logout' %}">
                  {% csrf_token %}
                </form>
              </div>

              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                <button form="logout-form" type="submit" type="button" class="btn btn-danger">Logout</button>
              </div>
            </div>
          </div>
        </div>
      </ul>
    </div>
  </div>
</nav>

templates/staff/components/sidebar.html
{% load static %}

<nav id="sidebar">
  <div class="p-4 pt-5">
    <div class="text-center">
      <img src="https://img.icons8.com/color/96/000000/change-user-male--v1.png" width="100" height="100">
    </div>
    <div class="text-center mb-5">{{ request.user }}</div>
    <ul class="list-unstyled components">
      <li>
        <a href="{% url 'home' %}">
          <i class="fa fa-tachometer mr-2"></i>Dashboard
        </a>
      </li>

      <li>
        <a href="#attendance" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
          <i class="fa fa-hourglass mr-2"></i>Manage Attendance
        </a>

        <ul class="collapse list-unstyled" id="attendance">
          <li>
            <a href="{% url 'attendance:new' %}">Take Attendance</a>
          </li>

          <li>
            <a href="{% url 'attendance:detail' %}">Update Attendance</a>
          </li>
        </ul>
      </li>

      <li>
        <a href="{% url 'leaves:new_staff' %}">
          <i class="fa fa-sign-out mr-2"></i>Apply for Leave
        </a>
      </li>

      <li>
        <a href="{% url 'feedback:new_staff' %}">
          <i class="fa fa-comment mr-2"></i>Feedback
        </a>
      </li>

      <li>
        <a href="#result" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
          <i class="fa fa-percent mr-2"></i>Manage Result
        </a>

        <ul class="collapse list-unstyled" id="result">
          <li>
            <a href="{% url 'results:new' %}">Add Result</a>
          </li>

          <li>
            <a href="{% url 'results:edit' %}">Edit Result</a>
          </li>
        </ul>
      </li>

      <li>
        <a href="{% url 'notifications:list_staff' %}">
          <i class="fa fa-bell mr-2"></i>Notifications
        </a>
      </li>
    </ul>
  </div>
</nav>