attendance/urls.py
from django.urls import path
from attendance.views import AttendanceCreateView, AttendanceDetailView, AttendanceUpdateView, AttendanceStudentView


urlpatterns = [
    path('new/', AttendanceCreateView.as_view(), name='new'),
    path('', AttendanceDetailView.as_view(), name='detail'),
    path('update/', AttendanceUpdateView.as_view(), name='update'),
    path('search/', AttendanceStudentView.as_view(), name='search')
]

kunai/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import (
    LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
)
from users.views import HomeView, UserLoginView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('attendance/', include(('attendance.urls', 'attendance'), namespace='attendance')),
    path('courses/', include(('courses.urls', 'courses'), namespace='courses')),
    path('feedback/', include(('feedback.urls', 'feedback'), namespace='feedback')),
    path('leaves/', include(('leaves.urls', 'leaves'), namespace='leaves')),
    path('notifications/', include(('notifications.urls', 'notifications'), namespace='notifications')),
    path('results/', include(('results.urls', 'results'), namespace='results')),
    path('session/', include(('session.urls', 'session'), namespace='session')),
    path('subjects/', include(('subjects.urls', 'subjects'), namespace='subjects')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('', HomeView.as_view(), name='home'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('password_reset/', PasswordResetView.as_view(template_name='password_reset.html'), name='password_reset'),
    path('password_reset_done/', PasswordResetDoneView.as_view(template_name='password_reset_done.html'), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'), name='password_reset_confirm'),
    path('password_reset_complete', PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), name='password_reset_complete'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users.views import StaffListView, StaffCreateView, StaffUpdateView, StudentListView, StudentCreateView, StudentUpdateView


urlpatterns = [
    path('staff/', StaffListView.as_view(), name='list_staff'),
    path('staff/new/', StaffCreateView.as_view(), name='new_staff'),
    path('staff/edit/<int:pk>', StaffUpdateView.as_view(), name='edit_staff'),
    path('students/', StudentListView.as_view(), name='list_student'),
    path('students/new/', StudentCreateView.as_view(), name='new_student'),
    path('students/edit/<int:pk>', StudentUpdateView.as_view(), name='edit_student'),
]

attendance/models.py
from django.db import models
from subjects.models import Subject
from users.models import Student
from session.models import Session


class Attendance(models.Model):
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    attendance_date = models.DateField()
    session = models.ForeignKey(Session, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class AttendanceReport(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    attendance = models.ForeignKey(Attendance, on_delete=models.CASCADE)
    status = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

attendance/forms.py
from django import forms
from django.forms import ModelForm
from attendance.models import Attendance


class DateInput(forms.DateInput):
    input_type = 'date'


class AttendanceForm(ModelForm):
    def __init__(self, *args, **kwargs):
        staff = kwargs.pop('staff', None)
        super().__init__(*args, **kwargs)
        if staff:
            self.fields['subject'].queryset = staff.subject_set.all()

    class Meta:
        model = Attendance
        fields = '__all__'
        widgets = {
            'attendance_date': DateInput(),
        }


class AttendanceUpdateForm(ModelForm):
    def __init__(self, *args, **kwargs):
        staff = kwargs.pop('staff', None)
        super().__init__(*args, **kwargs)
        if staff:
            self.fields['subject'].queryset = staff.subject_set.all()
            self.fields['attendance_date'] = forms.ChoiceField(choices=(('', '---------'),), label='Attendance Date')

    class Meta:
        model = Attendance
        fields = '__all__'


class AttendanceSearchForm(ModelForm):
    start_date = forms.DateField(widget=DateInput)
    end_date = forms.DateField(widget=DateInput)

    def __init__(self, *args, **kwargs):
        course = kwargs.pop('course', None)
        super().__init__(*args, **kwargs)
        if course:
            self.fields['subject'].queryset = course.subject_set.all()

    class Meta:
        model = Attendance
        fields = ('subject', 'start_date', 'end_date')
        widgets = {
            'start_date': DateInput(),
            'end_date': DateInput()
        }

attendance/views.py
from django.shortcuts import render, redirect, reverse
from django.http import JsonResponse, Http404
from django.views.generic import View, ListView, CreateView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from attendance.serializers import AttendanceSerializer, AttendanceReportSerializer
from attendance.models import Attendance, AttendanceReport
from users.models import Staff, Student
from subjects.models import Subject
from attendance.forms import AttendanceForm, AttendanceUpdateForm, AttendanceSearchForm


class AttendanceCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    template_name = 'staff/attendance/attendance_form.html'
    model = Attendance
    form_class = AttendanceForm

    def test_func(self):
        return True if self.request.user.user_type == '2' else False

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = AttendanceForm(staff=Staff.objects.get(user=self.request.user))
        return context

    def post(self, request, *args, **kwargs):
        super().post(request, *args, **kwargs)
        for student in Student.objects.filter(course=Subject.objects.get(id=request.POST['subject']).course):
            if str(student.id) in request.POST.getlist('student[]'):
                AttendanceReport.objects.create(attendance=self.object, student=student, status=True)
            else:
                AttendanceReport.objects.create(attendance=self.object, student=student, status=False)
        return redirect('home')

    def get_success_url(self, **kwargs):
        return reverse('home')


class AttendanceDetailView(LoginRequiredMixin, UserPassesTestMixin, View):
    template_name = 'staff/attendance/attendance_detail.html'

    def test_func(self):
        return True if self.request.user.user_type == '2' else False

    def get(self, request, *args, **kwargs):
        if request.is_ajax():
            attendance_reports = AttendanceReport.objects.filter(attendance_id=request.GET['attendance'])
            serialized_reports = AttendanceReportSerializer(attendance_reports, many=True).data
            return JsonResponse(serialized_reports, safe=False)
        context = {'form': AttendanceUpdateForm(staff=Staff.objects.get(user=self.request.user))}
        return render(request, self.template_name, context=context)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = AttendanceUpdateForm(staff=Staff.objects.get(user=self.request.user))
        return context


class AttendanceUpdateView(LoginRequiredMixin, UserPassesTestMixin, View):
    def test_func(self):
        return True if self.request.user.user_type == '2' else False

    def get(self, request, *args, **kwargs):
        if request.is_ajax():
            attendances = Attendance.objects.filter(subject_id=request.GET['subject'],
                                                    session_id=request.GET['session'])
            serialized_attendance = AttendanceSerializer(attendances, many=True).data
            return JsonResponse(serialized_attendance, safe=False)
        raise Http404

    def post(self, request, *args, **kwargs):
        attendance = Attendance.objects.get(id=request.POST['attendance_date'])
        for attendance_report in attendance.attendancereport_set.all():
            attendance_report.status = str(attendance_report.id) in request.POST.getlist('report[]')
            attendance_report.save()
        return redirect('home')


class AttendanceStudentView(LoginRequiredMixin, UserPassesTestMixin, View):
    template_name = 'student/attendance/attendance_search.html'

    def test_func(self):
        return True if self.request.user.user_type == '3' else False

    def get(self, request, *args, **kwargs):
        if 'start_date' in request.GET and 'end_date' in request.GET:
            attendances = Attendance.objects.filter(subject=request.GET['subject'], attendance_date__range=[
                                                    request.GET['start_date'], request.GET['end_date']])
            reports = []
            for attendance in attendances:
                report_qs = AttendanceReport.objects.filter(attendance=attendance, student=request.user.student)
                if report_qs.exists():
                    reports.append(report_qs[0])
            context = {'object_list': reports}
            return render(request, 'student/attendance/attendance_list.html', context=context)
        context = {'form': AttendanceSearchForm(course=request.user.student.course)}
        return render(request, self.template_name, context=context)

templates/staff/attendance/attendance_detail.html
{% extends 'staff/index.html' %}
{% load bootstrap4 %}

{% block content %}
<div class="card card-border shadow rounded mb-4">
  <div class="my-4 mx-4">
    <h3 class="text-center mb-5">View Attendance</h3>
    <form method="POST" action="{% url 'attendance:update' %}">
      {% csrf_token %}
      {% bootstrap_field form.subject layout="horizontal" %}
      {% bootstrap_field form.session layout="horizontal" %}
      <button id="fetch_dates" type="button" class="btn btn-block btn-primary my-5">Fetch Attendance Dates</button>

      <div id="attendance_select" class="d-none">
        {% bootstrap_field form.attendance_date layout="horizontal" %}
      </div>

      <div id="students_form" class="row mt-5"></div>

      <button id="submit_btn" type="submit" class="d-none btn btn-block btn-primary mt-5">Save</button>
    </form>
  </div>
</div>
{% endblock content %}

{% block javascript %}
<script>
  $("#fetch_dates").click(() => {
    let subject_id = ($("#id_subject").val());
    let session_id = ($("#id_session").val());
    if (subject_id && session_id) {
      $.ajax({
        url: `{% url 'attendance:update' %}?subject=${subject_id}&session=${session_id}`,
        method: "GET",
        success(response) {
          $("#attendance_select").removeClass("d-none");
          $("#student_select").removeClass("d-none");
          $("#id_attendance_date").html(`<option value>---------</option>`);
          for (let attendance of response) {
            $("#id_attendance_date").append(`<option value="${attendance.id}">${attendance.attendance_date}</option>`);
          }
        }
      })
    }
  });

  $("#id_attendance_date").change(() => {
    $("#students_form").html("");
    let attendance_id = ($("#id_attendance_date").val());
    if (attendance_id) {
      $.ajax({
        url: `{% url 'attendance:detail' %}?attendance=${attendance_id}`,
        method: "GET",
        success(response) {
          for (let attendance_report of response) {
            $("#submit_btn").removeClass("d-none");
            $("#students_form").removeClass("d-none");
            if (attendance_report.status) {
              $("#students_form").append(`<div class="col-lg-4 col-sm-6"><div class="form-group"><label for="student_${attendance_report.id}" class="col-form-label mr-2">${attendance_report.student.first_name} ${attendance_report.student.last_name} <b>[Present]</b></label><input class="mr-4" id="student_${attendance_report.id}" type="checkbox" checked name="report[]" value="${attendance_report.id}"></div></div>`);
            } else {
              $("#students_form").append(`<div class="col-lg-4 col-sm-6"><div class="form-group"><label for="student_${attendance_report.id}" class="col-form-label mr-2">${attendance_report.student.first_name} ${attendance_report.student.last_name} <b>[Absent]</b></label><input class="mr-4" id="student_${attendance_report.id}" type="checkbox" name="report[]" value="${attendance_report.id}"></div></div>`);
            }
          }
        }
      });
    }
  });
</script>
{% endblock javascript %}

templates/staff/attendance/attendance_form.html
{% extends 'staff/index.html' %}
{% load bootstrap4 %}

{% block content %}
<div class="card card-border shadow rounded mb-4">
  <div class="my-4 mx-4">
    <h3 class="text-center mb-5">Add Attendance</h3>
    <form method="POST">
      {% csrf_token %}
      {% bootstrap_field form.subject layout="horizontal" %}
      {% bootstrap_field form.session layout="horizontal" %}
      {% bootstrap_field form.attendance_date layout="horizontal" %}
      <button id="fetch_students" type="button" class="btn btn-block btn-primary my-5">Fetch Students</button>
      <div id="students_form" class="row mt-5"></div>
      <div id="save_btn" class="d-none">
        <button type="submit" class="btn btn-block btn-primary mt-5">Save</button>
      </div>
    </form>
  </div>
</div>
{% endblock content %}

{% block javascript %}
<script>
  $("#fetch_students").click(() => {
    $("#students_form").html("");
    let subject_id = ($("#id_subject").val());
    let session_id = ($("#id_session").val());
    if (session_id) {
      $.ajax({
        url: `{% url 'users:list_student' %}?subject=${subject_id}&session=${session_id}`,
        method: "GET",
        success(response) {
          $("#save_btn").removeClass("d-none");
          for (let student of response) {
            $("#students_form").append(`<div class="col-lg-4 col-sm-6"><div class="form-group"><label for="student_${student.id}" class="col-form-label mr-2">${student.first_name} ${student.last_name}</label><input class="mr-4" id="student_${student.id}" type="checkbox" checked name="student[]" value="${student.id}"></div></div>`);
          }
        }
      });
    }
  });
</script>
{% endblock javascript %}